//@version=5
indicator('MACD Sample Script 1', overlay=true)

// Calculate MACD
[macdLine, signalLine, _] = ta.macd(close, 12, 26, 9)

// Define the golden cross condition
goldenCross = ta.crossover(macdLine, signalLine)

// Define the death cross condition
deathCross = ta.crossunder(macdLine, signalLine)

// Use the alertcondition function to generate alerts
alertcondition(condition=goldenCross, title="MACD Golden Cross", message="")
alertcondition(condition=deathCross, title="MACD Death Cross", message="")



if goldenCross 
    label.new(bar_index, low, str.tostring("BUY"), color = color.lime, style = label.style_label_up)

if deathCross
    label.new(bar_index, low, str.tostring("SELL"), color = color.red, style = label.style_label_up)